print("hi")
print("Hens", 25 + 30 / 6)
print(3 + 2 < 5 - 7)
print("is it greater ?", 5 > -2)
print("How about some more.")
print("Is it greater or equal?", 5 >= -2)
print("Is it less or equal?", 5 <= -2)
